{
  pkgs,
  config,
  lib,
  ...
}:
let

  base = "#${config.lib.stylix.colors.base00}";
  mantle = "#${config.lib.stylix.colors.base01}";
  surface0 = "#${config.lib.stylix.colors.base02}";
  surface1 = "#${config.lib.stylix.colors.base03}";

  surface2 = "#${config.lib.stylix.colors.base04}";
  text = "#${config.lib.stylix.colors.base05}";
  rosewater = "#${config.lib.stylix.colors.base06}";
  _lavender = "#${config.lib.stylix.colors.base07}";

  red = "#${config.lib.stylix.colors.base08}";
  peach = "#${config.lib.stylix.colors.base09}";
  yellow = "#${config.lib.stylix.colors.base0A}";
  green = "#${config.lib.stylix.colors.base0B}";
  teal = "#${config.lib.stylix.colors.base0C}";
  blue = "#${config.lib.stylix.colors.base0D}";
  purple = "#${config.lib.stylix.colors.base0E}";
  _flamingo = "#${config.lib.stylix.colors.base0F}";

  font = "${config.stylix.fonts.monospace.name}";
  fontSize = "${toString config.stylix.fonts.sizes.desktop}";
in
{

  home.packages = with pkgs; [
    hyprpicker
    gpu-screen-recorder
  ];

  wayland.windowManager.hyprland.settings.exec-once = [ "hyprpanel -b hypr" ];

  home.activation = {
    downloads = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run mkdir -p ${config.home.homeDirectory}/Downloads'';
    documents = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run mkdir -p ${config.home.homeDirectory}/Documents'';
    pictures = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run mkdir -p ${config.home.homeDirectory}/Pictures'';
    projects = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run mkdir -p ${config.home.homeDirectory}/Projects'';
    videos = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run mkdir -p ${config.home.homeDirectory}/Videos'';
    cleanHyprpanel = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] ''run rm -rf ${config.home.homeDirectory}/.cache/ags/hyprpanel'';
  };

  # "*" mean : all monitors. We can provide specific monitors with its number.
  # e.g. "2": {"left": []}
  home.file.".cache/ags/hyprpanel/options.json" = {
    text = # json
      ''
        {
          "bar.layouts": {
            "*": {
              "left": ["dashboard", "workspaces", "windowtitle", "battery", "ram", "cpu", "storage", "netstat"],
              "center": ["media", "update"],
              "right": ["volume", "network", "bluetooth", "systray", "clock", "notifications"]
            }
          },
          
          "bar.workspaces": {
            "windowtitle.label": true,
            "volume.label": true,
            "network.truncation_size": 12,
            "bluetooth.label": true,
            "clock.format": "%a %b %e  %H:%M",
            "notifications.show_total": true,

            "monitorSpecific": true,
            "hideUnoccupied": true,
            "workspaces": 5,
            "numbered_active_indicator": "highlight",
            "showWsIcons": true,
            "workspaceIconMap": {
              "[dD]iscord": "󰙯",
              "title:YouTube": "",
              "class:kitty": "󰄛",
              "class:Opera": ""
            }
          },

          "bar.customModules.storage.leftClick": "gdu",
          "bar.customModules.cpu.leftClick": "btop",
          "bar.customModules.ram.leftClick": "btop",
          "bar.customModules.netstat.leftClick": "btop",
          "bar.customModules.updates.leftClick": "rebuild",

          "menus.dashboard.stats.enable_gpu": true,

          "menus.dashboard.shortcuts.left.shortcut1.icon": "",
          "menus.dashboard.shortcuts.left.shortcut1.command": "opera",
          "menus.dashboard.shortcuts.left.shortcut1.tooltip": "Opera",
          "menus.dashboard.shortcuts.left.shortcut4.icon": "",
          "menus.dashboard.shortcuts.left.shortcut4.command": "ags -t applauncher",
          "menus.dashboard.shortcuts.left.shortcut4.tooltip": "Search Apps",

          "menus.dashboard.directories.left.directory1.label": "󰉍 Downloads",
          "menus.dashboard.directories.left.directory1.command": "kitty ${config.home.homeDirectory}/Downloads/",
          "menus.dashboard.directories.left.directory2.label": "󱧶 Documents",
          "menus.dashboard.directories.left.directory2.command": "kitty ${config.home.homeDirectory}/Documents/",
          "menus.dashboard.directories.left.directory3.label": "󰉏 Pictures",
          "menus.dashboard.directories.left.directory3.command": "kitty ${config.home.homeDirectory}/Pictures/",
          "menus.dashboard.directories.right.directory1.label": "󱄅 Nix",
          "menus.dashboard.directories.right.directory1.command": "kitty ${config.home.homeDirectory}/Nix/",
          "menus.dashboard.directories.right.directory2.label": "󰚝 Projects",
          "menus.dashboard.directories.right.directory2.command": "kitty ${config.home.homeDirectory}/Projects/",
          "menus.dashboard.directories.right.directory3.label": "󰉏 Videos",
          "menus.dashboard.directories.right.directory3.command": "kitty ${config.home.homeDirectory}/Videos/",


          "theme.font.name": "${font}",
          "theme.font.size": "${fontSize}px",
          "bar.launcher.icon": "",
          "wallpaper.enable": false,

          "theme.bar.buttons.dashboard.enableBorder": true,
          "theme.bar.menus.menu.notifications.scrollbar.color"                 : "${blue}",
          "theme.bar.menus.menu.notifications.pager.label"                     : "${surface2}",
          "theme.bar.menus.menu.notifications.pager.button"                    : "${blue}",
          "theme.bar.menus.menu.notifications.pager.background"                : "${base}",
          "theme.bar.menus.menu.notifications.switch.puck"                     : "${surface0}",
          "theme.bar.menus.menu.notifications.switch.disabled"                 : "${mantle}",
          "theme.bar.menus.menu.notifications.switch.enabled"                  : "${blue}",
          "theme.bar.menus.menu.notifications.clear"                           : "${blue}",
          "theme.bar.menus.menu.notifications.switch_divider"                  : "${surface0}",
          "theme.bar.menus.menu.notifications.border"                          : "${mantle}",
          "theme.bar.menus.menu.notifications.card"                            : "${mantle}",
          "theme.bar.menus.menu.notifications.background"                      : "${base}",
          "theme.bar.menus.menu.notifications.no_notifications_label"          : "${mantle}",
          "theme.bar.menus.menu.notifications.label"                           : "${blue}",
          "theme.bar.menus.menu.power.buttons.sleep.icon"                      : "${mantle}",
          "theme.bar.menus.menu.power.buttons.sleep.text"                      : "${blue}",
          "theme.bar.menus.menu.power.buttons.sleep.icon_background"           : "${blue}",
          "theme.bar.menus.menu.power.buttons.sleep.background"                : "${base}",
          "theme.bar.menus.menu.power.buttons.logout.icon"                     : "${mantle}",
          "theme.bar.menus.menu.power.buttons.logout.text"                     : "${green}",
          "theme.bar.menus.menu.power.buttons.logout.icon_background"          : "${green}",
          "theme.bar.menus.menu.power.buttons.logout.background"               : "${base}",
          "theme.bar.menus.menu.power.buttons.restart.icon"                    : "${mantle}",
          "theme.bar.menus.menu.power.buttons.restart.text"                    : "${peach}",
          "theme.bar.menus.menu.power.buttons.restart.icon_background"         : "${peach}",
          "theme.bar.menus.menu.power.buttons.restart.background"              : "${base}",
          "theme.bar.menus.menu.power.buttons.shutdown.icon"                   : "${mantle}",
          "theme.bar.menus.menu.power.buttons.shutdown.text"                   : "${red}",
          "theme.bar.menus.menu.power.buttons.shutdown.icon_background"        : "${red}",
          "theme.bar.menus.menu.power.buttons.shutdown.background"             : "${base}",
          "theme.bar.menus.menu.power.border.color"                            : "${mantle}",
          "theme.bar.menus.menu.power.background.color"                        : "${base}",
          "theme.bar.menus.menu.dashboard.monitors.disk.label"                 : "${purple}",
          "theme.bar.menus.menu.dashboard.monitors.disk.bar"                   : "${purple}",
          "theme.bar.menus.menu.dashboard.monitors.disk.icon"                  : "${purple}",
          "theme.bar.menus.menu.dashboard.monitors.gpu.label"                  : "${green}",
          "theme.bar.menus.menu.dashboard.monitors.gpu.bar"                    : "${green}",
          "theme.bar.menus.menu.dashboard.monitors.gpu.icon"                   : "${green}",
          "theme.bar.menus.menu.dashboard.monitors.ram.label"                  : "${yellow}",
          "theme.bar.menus.menu.dashboard.monitors.ram.bar"                    : "${yellow}",
          "theme.bar.menus.menu.dashboard.monitors.ram.icon"                   : "${yellow}",
          "theme.bar.menus.menu.dashboard.monitors.cpu.label"                  : "${red}",
          "theme.bar.menus.menu.dashboard.monitors.cpu.bar"                    : "${red}",
          "theme.bar.menus.menu.dashboard.monitors.cpu.icon"                   : "${red}",
          "theme.bar.menus.menu.dashboard.directories.right.bottom.color"      : "${blue}",
          "theme.bar.menus.menu.dashboard.directories.right.top.color"         : "${teal}",
          "theme.bar.menus.menu.dashboard.directories.left.bottom.color"       : "${red}",
          "theme.bar.menus.menu.dashboard.directories.left.middle.color"       : "${yellow}",
          "theme.bar.menus.menu.dashboard.directories.left.top.color"          : "${purple}",
          "theme.bar.menus.menu.dashboard.controls.input.text"                 : "${mantle}",
          "theme.bar.menus.menu.dashboard.controls.input.background"           : "${purple}",
          "theme.bar.menus.menu.dashboard.controls.volume.text"                : "${mantle}",
          "theme.bar.menus.menu.dashboard.controls.volume.background"          : "${red}",
          "theme.bar.menus.menu.dashboard.controls.notifications.text"         : "${mantle}",
          "theme.bar.menus.menu.dashboard.controls.notifications.background"   : "${yellow}",
          "theme.bar.menus.menu.dashboard.controls.bluetooth.text"             : "${mantle}",
          "theme.bar.menus.menu.dashboard.controls.wifi.text"                  : "${mantle}",
          "theme.bar.menus.menu.dashboard.controls.disabled"                   : "${surface1}",
          "theme.bar.menus.menu.dashboard.shortcuts.recording"                 : "${green}",
          "theme.bar.menus.menu.dashboard.shortcuts.text"                      : "${mantle}",
          "theme.bar.menus.menu.dashboard.shortcuts.background"                : "${blue}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.button_text"  : "${base}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.deny"         : "${purple}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.confirm"      : "${teal}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.body"         : "${rosewater}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.label"        : "${blue}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.border"       : "${mantle}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.background"   : "${base}",
          "theme.bar.menus.menu.dashboard.powermenu.confirmation.card"         : "${mantle}",
          "theme.bar.menus.menu.dashboard.powermenu.sleep"                     : "${blue}",
          "theme.bar.menus.menu.dashboard.powermenu.logout"                    : "${green}",
          "theme.bar.menus.menu.dashboard.powermenu.restart"                   : "${peach}",
          "theme.bar.menus.menu.dashboard.powermenu.shutdown"                  : "${red}",
          "theme.bar.menus.menu.dashboard.profile.name"                        : "${purple}",
          "theme.bar.menus.menu.dashboard.border.color"                        : "${mantle}",
          "theme.bar.menus.menu.dashboard.background.color"                    : "${base}",
          "theme.bar.menus.menu.dashboard.card.color"                          : "${mantle}",
          "theme.bar.menus.menu.clock.weather.hourly.temperature"              : "${purple}",
          "theme.bar.menus.menu.clock.weather.hourly.icon"                     : "${purple}",
          "theme.bar.menus.menu.clock.weather.hourly.time"                     : "${purple}",
          "theme.bar.menus.menu.clock.weather.thermometer.extremelycold"       : "${blue}",
          "theme.bar.menus.menu.clock.weather.thermometer.cold"                : "${teal}",
          "theme.bar.menus.menu.clock.weather.thermometer.moderate"            : "${yellow}",
          "theme.bar.menus.menu.clock.weather.thermometer.hot"                 : "${peach}",
          "theme.bar.menus.menu.clock.weather.thermometer.extremelyhot"        : "${red}",
          "theme.bar.menus.menu.clock.weather.stats"                           : "${purple}",
          "theme.bar.menus.menu.clock.weather.status"                          : "${teal}",
          "theme.bar.menus.menu.clock.weather.temperature"                     : "${rosewater}",
          "theme.bar.menus.menu.clock.weather.icon"                            : "${purple}",
          "theme.bar.menus.menu.clock.calendar.contextdays"                    : "${surface1}",
          "theme.bar.menus.menu.clock.calendar.days"                           : "${rosewater}",
          "theme.bar.menus.menu.clock.calendar.currentday"                     : "${purple}",
          "theme.bar.menus.menu.clock.calendar.paginator"                      : "${purple}",
          "theme.bar.menus.menu.clock.calendar.weekdays"                       : "${purple}",
          "theme.bar.menus.menu.clock.calendar.yearmonth"                      : "${teal}",
          "theme.bar.menus.menu.clock.time.timeperiod"                         : "${teal}",
          "theme.bar.menus.menu.clock.time.time"                               : "${purple}",
          "theme.bar.menus.menu.clock.text"                                    : "${rosewater}",
          "theme.bar.menus.menu.clock.border.color"                            : "${mantle}",
          "theme.bar.menus.menu.clock.background.color"                        : "${base}",
          "theme.bar.menus.menu.clock.card.color"                              : "${mantle}",
          "theme.bar.menus.menu.battery.slider.puck"                           : "${surface1}",
          "theme.bar.menus.menu.battery.slider.backgroundhover"                : "${surface0}",
          "theme.bar.menus.menu.battery.slider.background"                     : "${surface1}",
          "theme.bar.menus.menu.battery.slider.primary"                        : "${yellow}",
          "theme.bar.menus.menu.battery.icons.active"                          : "${yellow}",
          "theme.bar.menus.menu.battery.icons.passive"                         : "${surface2}",
          "theme.bar.menus.menu.battery.listitems.active"                      : "${yellow}",
          "theme.bar.menus.menu.battery.listitems.passive"                     : "${rosewater}",
          "theme.bar.menus.menu.battery.text"                                  : "${rosewater}",
          "theme.bar.menus.menu.battery.label.color"                           : "${yellow}",
          "theme.bar.menus.menu.battery.border.color"                          : "${mantle}",
          "theme.bar.menus.menu.battery.background.color"                      : "${base}",
          "theme.bar.menus.menu.battery.card.color"                            : "${mantle}",
          "theme.bar.menus.menu.systray.dropdownmenu.divider"                  : "${base}",
          "theme.bar.menus.menu.systray.dropdownmenu.text"                     : "${rosewater}",
          "theme.bar.menus.menu.systray.dropdownmenu.background"               : "${base}",
          "theme.bar.menus.menu.bluetooth.iconbutton.active"                   : "${blue}",
          "theme.bar.menus.menu.bluetooth.iconbutton.passive"                  : "${rosewater}",
          "theme.bar.menus.menu.bluetooth.icons.active"                        : "${blue}",
          "theme.bar.menus.menu.bluetooth.icons.passive"                       : "${surface2}",
          "theme.bar.menus.menu.bluetooth.listitems.active"                    : "${blue}",
          "theme.bar.menus.menu.bluetooth.listitems.passive"                   : "${rosewater}",
          "theme.bar.menus.menu.bluetooth.switch.puck"                         : "${surface0}",
          "theme.bar.menus.menu.bluetooth.switch.disabled"                     : "${mantle}",
          "theme.bar.menus.menu.bluetooth.switch.enabled"                      : "${blue}",
          "theme.bar.menus.menu.bluetooth.switch_divider"                      : "${surface0}",
          "theme.bar.menus.menu.bluetooth.status"                              : "${surface1}",
          "theme.bar.menus.menu.bluetooth.text"                                : "${rosewater}",
          "theme.bar.menus.menu.bluetooth.label.color"                         : "${blue}",
          "theme.bar.menus.menu.bluetooth.border.color"                        : "${mantle}",
          "theme.bar.menus.menu.network.icons.passive"                         : "${surface2}",
          "theme.bar.menus.menu.network.listitems.passive"                     : "${rosewater}",
          "theme.bar.menus.menu.network.text"                                  : "${rosewater}",
          "theme.bar.menus.menu.network.border.color"                          : "${mantle}",
          "theme.bar.menus.menu.network.background.color"                      : "${base}",
          "theme.bar.menus.menu.network.card.color"                            : "${mantle}",
          "theme.bar.menus.menu.volume.input_slider.puck"                      : "${surface1}",
          "theme.bar.menus.menu.volume.input_slider.backgroundhover"           : "${surface0}",
          "theme.bar.menus.menu.volume.input_slider.background"                : "${surface1}",
          "theme.bar.menus.menu.volume.input_slider.primary"                   : "${peach}",
          "theme.bar.menus.menu.volume.audio_slider.puck"                      : "${surface1}",
          "theme.bar.menus.menu.volume.audio_slider.backgroundhover"           : "${surface0}",
          "theme.bar.menus.menu.volume.audio_slider.background"                : "${surface1}",
          "theme.bar.menus.menu.volume.audio_slider.primary"                   : "${peach}",
          "theme.bar.menus.menu.volume.icons.active"                           : "${peach}",
          "theme.bar.menus.menu.volume.icons.passive"                          : "${surface2}",
          "theme.bar.menus.menu.volume.iconbutton.active"                      : "${peach}",
          "theme.bar.menus.menu.volume.iconbutton.passive"                     : "${rosewater}",
          "theme.bar.menus.menu.volume.listitems.active"                       : "${peach}",
          "theme.bar.menus.menu.volume.listitems.passive"                      : "${rosewater}",
          "theme.bar.menus.menu.volume.text"                                   : "${rosewater}",
          "theme.bar.menus.menu.volume.label.color"                            : "${peach}",
          "theme.bar.menus.menu.volume.border.color"                           : "${mantle}",
          "theme.bar.menus.menu.volume.background.color"                       : "${base}",
          "theme.bar.menus.menu.volume.card.color"                             : "${mantle}",
          "theme.bar.menus.menu.media.slider.puck"                             : "${surface1}",
          "theme.bar.menus.menu.media.slider.backgroundhover"                  : "${surface0}",
          "theme.bar.menus.menu.media.slider.background"                       : "${surface1}",
          "theme.bar.menus.menu.media.slider.primary"                          : "${purple}",
          "theme.bar.menus.menu.media.buttons.text"                            : "${base}",
          "theme.bar.menus.menu.media.buttons.background"                      : "${blue}",
          "theme.bar.menus.menu.media.buttons.enabled"                         : "${teal}",
          "theme.bar.menus.menu.media.buttons.inactive"                        : "${surface1}",
          "theme.bar.menus.menu.media.border.color"                            : "${mantle}",
          "theme.bar.menus.menu.media.card.color"                              : "${mantle}",
          "theme.bar.menus.menu.media.background.color"                        : "${base}",
          "theme.bar.menus.menu.media.album"                                   : "${purple}",
          "theme.bar.menus.menu.media.artist"                                  : "${teal}",
          "theme.bar.menus.menu.media.song"                                    : "${blue}",
          "theme.bar.menus.tooltip.text"                                       : "${rosewater}",
          "theme.bar.menus.tooltip.background"                                 : "${base}",
          "theme.bar.menus.dropdownmenu.divider"                               : "${base}",
          "theme.bar.menus.dropdownmenu.text"                                  : "${rosewater}",
          "theme.bar.menus.dropdownmenu.background"                            : "${base}",
          "theme.bar.menus.slider.puck"                                        : "${surface1}",
          "theme.bar.menus.slider.backgroundhover"                             : "${surface0}",
          "theme.bar.menus.slider.background"                                  : "${surface1}",
          "theme.bar.menus.slider.primary"                                     : "${blue}",
          "theme.bar.menus.progressbar.background"                             : "${surface0}",
          "theme.bar.menus.progressbar.foreground"                             : "${blue}",
          "theme.bar.menus.iconbuttons.active"                                 : "${blue}",
          "theme.bar.menus.iconbuttons.passive"                                : "${rosewater}",
          "theme.bar.menus.buttons.text"                                       : "${mantle}",
          "theme.bar.menus.buttons.disabled"                                   : "${surface1}",
          "theme.bar.menus.buttons.active"                                     : "${purple}",
          "theme.bar.menus.buttons.default"                                    : "${blue}",
          "theme.bar.menus.check_radio_button.active"                          : "${blue}",
          "theme.bar.menus.check_radio_button.background"                      : "${mantle}",
          "theme.bar.menus.switch.puck"                                        : "${surface0}",
          "theme.bar.menus.switch.disabled"                                    : "${mantle}",
          "theme.bar.menus.switch.enabled"                                     : "${blue}",
          "theme.bar.menus.icons.active"                                       : "${blue}",
          "theme.bar.menus.icons.passive"                                      : "${surface1}",
          "theme.bar.menus.listitems.active"                                   : "${blue}",
          "theme.bar.menus.listitems.passive"                                  : "${rosewater}",
          "theme.bar.menus.popover.border"                                     : "${mantle}",
          "theme.bar.menus.popover.background"                                 : "${mantle}",
          "theme.bar.menus.popover.text"                                       : "${blue}",
          "theme.bar.menus.label"                                              : "${blue}",
          "theme.bar.menus.feinttext"                                          : "${mantle}",
          "theme.bar.menus.dimtext"                                            : "${surface1}",
          "theme.bar.menus.text"                                               : "${rosewater}",
          "theme.bar.menus.border.color"                                       : "${mantle}",
          "theme.bar.menus.cards"                                              : "${mantle}",
          "theme.bar.menus.background"                                         : "${base}",
          "theme.bar.buttons.modules.power.icon_background"                    : "${base}",
          "theme.bar.buttons.modules.power.icon"                               : "${red}",
          "theme.bar.buttons.modules.power.background"                         : "${mantle}",
          "theme.bar.buttons.modules.weather.icon_background"                  : "${mantle}",
          "theme.bar.buttons.modules.weather.icon"                             : "${peach}",
          "theme.bar.buttons.modules.weather.text"                             : "${peach}",
          "theme.bar.buttons.modules.updates.icon_background"                  : "${mantle}",
          "theme.bar.buttons.modules.updates.background"                       : "${mantle}",
          "theme.bar.buttons.modules.kbLayout.icon_background"                 : "${mantle}",
          "theme.bar.buttons.modules.kbLayout.icon"                            : "${blue}",
          "theme.bar.buttons.modules.kbLayout.text"                            : "${blue}",
          "theme.bar.buttons.modules.kbLayout.background"                      : "${mantle}",
          "theme.bar.buttons.modules.netstat.icon_background"                  : "${mantle}",
          "theme.bar.buttons.modules.netstat.icon"                             : "${green}",
          "theme.bar.buttons.modules.netstat.text"                             : "${green}",
          "theme.bar.buttons.modules.netstat.background"                       : "${mantle}",
          "theme.bar.buttons.modules.storage.icon_background"                  : "${mantle}",
          "theme.bar.buttons.modules.storage.icon"                             : "${blue}",
          "theme.bar.buttons.modules.storage.text"                             : "${blue}",
          "theme.bar.buttons.modules.storage.background"                       : "${mantle}",
          "theme.bar.buttons.modules.cpu.icon_background"                      : "${mantle}",
          "theme.bar.buttons.modules.cpu.icon"                                 : "${purple}",
          "theme.bar.buttons.modules.cpu.text"                                 : "${purple}",
          "theme.bar.buttons.modules.cpu.background"                           : "${mantle}",
          "theme.bar.buttons.modules.ram.icon_background"                      : "${mantle}",
          "theme.bar.buttons.modules.ram.icon"                                 : "${yellow}",
          "theme.bar.buttons.modules.ram.text"                                 : "${yellow}",
          "theme.bar.buttons.modules.ram.background"                           : "${mantle}",
          "theme.bar.buttons.notifications.total"                              : "${blue}",
          "theme.bar.buttons.notifications.icon_background"                    : "${blue}",
          "theme.bar.buttons.notifications.icon"                               : "${blue}",
          "theme.bar.buttons.notifications.background"                         : "${mantle}",
          "theme.bar.buttons.clock.icon_background"                            : "${purple}",
          "theme.bar.buttons.clock.icon"                                       : "${purple}",
          "theme.bar.buttons.clock.text"                                       : "${purple}",
          "theme.bar.buttons.clock.background"                                 : "${mantle}",
          "theme.bar.buttons.battery.icon_background"                          : "${yellow}",
          "theme.bar.buttons.battery.icon"                                     : "${yellow}",
          "theme.bar.buttons.battery.text"                                     : "${yellow}",
          "theme.bar.buttons.battery.background"                               : "${mantle}",
          "theme.bar.buttons.systray.background"                               : "${mantle}",
          "theme.bar.buttons.bluetooth.icon_background"                        : "${blue}",
          "theme.bar.buttons.bluetooth.icon"                                   : "${blue}",
          "theme.bar.buttons.bluetooth.background"                             : "${mantle}",
          "theme.bar.buttons.network.background"                               : "${mantle}",
          "theme.bar.buttons.volume.icon_background"                           : "${peach}",
          "theme.bar.buttons.volume.icon"                                      : "${peach}",
          "theme.bar.buttons.volume.text"                                      : "${peach}",
          "theme.bar.buttons.volume.background"                                : "${mantle}",
          "theme.bar.buttons.media.icon_background"                            : "${blue}",
          "theme.bar.buttons.media.icon"                                       : "${blue}",
          "theme.bar.buttons.media.text"                                       : "${blue}",
          "theme.bar.buttons.media.background"                                 : "${mantle}",
          "theme.bar.buttons.windowtitle.icon_background"                      : "${purple}",
          "theme.bar.buttons.windowtitle.icon"                                 : "${purple}",
          "theme.bar.buttons.windowtitle.text"                                 : "${purple}",
          "theme.bar.buttons.windowtitle.background"                           : "${mantle}",
          "theme.bar.buttons.workspaces.numbered_active_underline_color"       : "${text}",
          "theme.bar.buttons.workspaces.numbered_active_highlighted_text_color": "${base}",
          "theme.bar.buttons.workspaces.active"                                : "${purple}",
          "theme.bar.buttons.workspaces.occupied"                              : "${red}",
          "theme.bar.buttons.workspaces.available"                             : "${blue}",
          "theme.bar.buttons.workspaces.hover"                                 : "${surface0}",
          "theme.bar.buttons.workspaces.background"                            : "${mantle}",
          "theme.bar.buttons.dashboard.icon"                                   : "${yellow}",
          "theme.bar.buttons.dashboard.background"                             : "${mantle}",
          "theme.bar.buttons.icon"                                             : "${blue}",
          "theme.bar.buttons.text"                                             : "${blue}",
          "theme.bar.buttons.hover"                                            : "${surface0}",
          "theme.bar.buttons.icon_background"                                  : "${mantle}",
          "theme.bar.buttons.background"                                       : "${mantle}",
          "theme.bar.buttons.style"                                            : "default",
          "theme.bar.background"                                               : "${base}",
          "theme.osd.label"                                                    : "${blue}",
          "theme.osd.icon"                                                     : "${base}",
          "theme.osd.bar_overflow_color"                                       : "${red}",
          "theme.osd.bar_empty_color"                                          : "${mantle}",
          "theme.osd.bar_color"                                                : "${blue}",
          "theme.osd.icon_container"                                           : "${blue}",
          "theme.osd.bar_container"                                            : "${base}",
          "theme.notification.close_button.label"                              : "${base}",
          "theme.notification.close_button.background"                         : "${blue}",
          "theme.notification.labelicon"                                       : "${blue}",
          "theme.notification.text"                                            : "${rosewater}",
          "theme.notification.time"                                            : "${surface2}",
          "theme.notification.border"                                          : "${mantle}",
          "theme.notification.label"                                           : "${blue}",
          "theme.notification.actions.text"                                    : "${mantle}",
          "theme.notification.actions.background"                              : "${blue}",
          "theme.notification.background"                                      : "${mantle}",
          "theme.bar.buttons.modules.weather.border"                           : "${peach}",
          "theme.bar.buttons.modules.kbLayout.border"                          : "${blue}",
          "theme.bar.buttons.modules.netstat.border"                           : "${green}",
          "theme.bar.buttons.modules.storage.border"                           : "${blue}",
          "theme.bar.buttons.modules.cpu.border"                               : "${purple}",
          "theme.bar.buttons.modules.ram.border"                               : "${yellow}",
          "theme.bar.buttons.notifications.border"                             : "${blue}",
          "theme.bar.buttons.clock.border"                                     : "${purple}",
          "theme.bar.buttons.battery.border"                                   : "${yellow}",
          "theme.bar.buttons.bluetooth.border"                                 : "${blue}",
          "theme.bar.buttons.volume.border"                                    : "${peach}",
          "theme.bar.buttons.media.border"                                     : "${blue}",
          "theme.bar.buttons.windowtitle.border"                               : "${purple}",
          "theme.bar.buttons.workspaces.border"                                : "${text}",
          "theme.bar.buttons.dashboard.border"                                 : "${yellow}",
          "theme.bar.buttons.modules.submap.background"                        : "${mantle}",
          "theme.bar.buttons.modules.submap.text"                              : "${teal}",
          "theme.bar.buttons.modules.submap.border"                            : "${teal}",
          "theme.bar.buttons.modules.submap.icon"                              : "${teal}",
          "theme.bar.buttons.modules.submap.icon_background"                   : "${mantle}"
        }
      '';
  };
}
